# Generated by Django 3.1.5 on 2021-08-16 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
