# Generated by Django 3.1.5 on 2021-08-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210816_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name_plural': 'Create Analysis'},
        ),
    ]
