# Generated by Django 3.1.5 on 2021-08-18 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210817_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
