# Generated by Django 3.1.5 on 2021-08-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20210818_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='post_body',
            field=models.TextField(blank=True, max_length=2200, null=True),
        ),
    ]
