# Generated by Django 3.1.5 on 2021-08-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20210819_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='post_body',
            field=models.TextField(blank=True, max_length=2200, null=True, verbose_name='your analysis'),
        ),
    ]
