# Generated by Django 3.1.5 on 2021-08-19 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0007_analysis_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='dis_likes',
            field=models.ManyToManyField(related_name='analysis_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='likes',
            field=models.ManyToManyField(related_name='analysis_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
