# Generated by Django 3.1.5 on 2021-08-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='Date_posted',
            new_name='date_posted',
        ),
    ]
